### ISSUE TITLE
Issue breakage

### ISSUE THREAD

**Issue by ericmjonas** [pywren/pywren#127]
Did we break exceptions on the latest master? 
```
import sys
import pywren

def hello_world(x):
    1/0
    return data


wrenexec = pywren.default_executor()
futures = wrenexec.map(hello_world, [None])

pywren.wait(futures)
```

gives
```
line-integral:pywren jonas$ python pywren-flow/importtest.py
Traceback (most recent call last):
  File "pywren-flow/importtest.py", line 12, in <module>
    pywren.wait(futures)
  File "/Users/jonas/projects/pywren/pywren/pywren/wait.py", line 44, in wait
    fs_dones, fs_notdones = _wait(fs, THREADPOOL_SIZE)
  File "/Users/jonas/projects/pywren/pywren/pywren/wait.py", line 110, in _wait
    pool.map(test, f_to_wait_on)
  File "/Users/jonas/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/jonas/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: ("'Traceback' object has no attribute 'tb_next'", <function unpickle_traceback at 0x10e9d91b8>, (<tblib.Frame object at 0x1167580d0>, 30, <tblib.Traceback object at 0x116761e10>))
```

**Comment by ericmjonas** [comment]
Indeed the test ```pytest test_simple.py::SimpleAsync::test_exception``` was broken here too, although travis kept passing fine. Further investigation yielded my local machine had `tblib 1.3.0` and the remote had `tblib 1.3.2`. Upgrading locally fixed it. 

This is a rare case, but it is disconcerting that tblib has backwards-compatibility-breaking changes on such a short timescale.

**Comment by shivaram** [comment]
I guess the numba problem was also related to minor version changes right ? Is this something we can either point out as warnings when a job is run ?
