### ISSUE TITLE
I can't run test function

### ISSUE THREAD

**Issue by higumachan** [pywren/pywren#156]
Hi, I want to run pywren.
But, I got this error when I'm running script.

```bash
pywren test_function
```

``` 
Traceback (most recent call last):
  File "/Users/kuma/.pyenv/versions/abeja-dsf/bin/pywren", line 11, in <module>
    sys.exit(main())
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/pywren/scripts/pywrencli.py", line 572, in main
    return cli(obj={})
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/pywren/scripts/pywrencli.py", line 374, in test_function
    res = fut.result() 
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/pywren/future.py", line 194, in result
    reraise(*self._traceback)
  File "/Users/kuma/.pyenv/versions/3.5.3/envs/abeja-dsf/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/task/jobrunner.py", line 27, in <module>
  File "/tmp/condaruntime/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 800, in _make_skel_func
  File "/tmp/condaruntime/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 792, in _reconstruct_closure
TypeError: 'int' object is not iterable
```

**Comment by apengwin** [comment]
@higumachan  this might be an issue with cloudpickle versioning. 
Can you try `pip install cloudpickle=0.2`?
