### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by cwharland** [pywren/pywren#219]
Seem to have hit an odd error I can't figure out by digging through the source.  I have a function that processes a csv file on s3 and places the result on s3. When invoking the function through `pywren` by mapping it over batches of input file names I'm getting:

```python
Traceback (most recent call last):
  File "process_files.py", line 121, in <module>
    df_results = process_csv(file_name)
  File "process_files.py", line 107, in process_csv
    results = [f.result() for f in futures]
  File "process_files.py", line 107, in <listcomp>
    results = [f.result() for f in futures]
  File "/venv/site-packages/pywren/future.py", line 202, in result
    reraise(*self._traceback)
  File "/venv/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/var/task/jobrunner.py", line 29, in <module>
  File "/tmp/pymodules/pywren/serialize/cloudpickle/cloudpickle.py", line 718, in subimport
ModuleNotFoundError: No module named 'pandas'
```

Am in interpreting the docs right in that pywren uses anaconda as execution environment? Is it possible that my local python venv is pickling something incorrectly?

A more general question might be: what are the best practices for using third party libraries with `pywren`? Should they be separate lambdas called from a coordinating `pywren` execution? Should I be using stand alone mode?

**Comment by ericmjonas** [comment]
Hi Chris ! We do in fact use anaconda as an execution environment, but behind the scenes we download a pre-packaged runtime where we've already installed a bunch of packages. Our serialization layer does its best to import/marshal any other libraries your code might depend on, but it can't serialize c-based modules like pandas. 

@craig_wilkins on twitter had this problem with pandas, so we tried building him a custom python 3.6 runtime. https://twitter.com/stochastician/status/907264445763567616 is the exchange. 

Right now, the way runtimes are built is a little complicated, but we're working on improving it. Can I ask -- how familiar are you with the python / anaconda ecosystem? What about tools like docker? I'd love to figure out the right way of making this work for you.

**Comment by cwharland** [comment]
We solved it two ways:
1) swapped pandas for stdlib stuff (hammer approach)
2) Created lambdas with guaranteed runtime environments via chalice and then used pywren to call them in parallel as a coordinator. This means pywren just calls a URL (api gateway) or does a direct lambda invoke.

**Comment by mrechung** [comment]
Hi, I am also having the same problem @ericmjonas. Is it possible to make a custom python 2.7 data science runtime? I would appreciate it greatly. I also just need pandas, numpy and scikit learn. Thanks!

**Comment by JiaweiZhuang** [comment]
> Right now, the way runtimes are built is a little complicated, but we're working on improving it. Can I ask -- how familiar are you with the python / anaconda ecosystem? What about tools like docker? I'd love to figure out the right way of making this work for you.

I am also interested in packing my own Python runtime. Either Conda or Docker would be good for me. Do you have any instructions for how to do this? Thanks!

In particular, I'd like to use the [xarray](https://xarray.pydata.org) and [NetCDF4](http://unidata.github.io/netcdf4-python/) libraries. With Anaconda, the installation is simply:
```
conda install xarray netcdf4
```

For your reference, xarray is a multi-dimensional extension to pandas (so it relies on pandas). It reads and writes NetCDF format, which is the most widely used data format in Earth science. I want to see if it is possible to combine them with pywren to process [Public Earth science datasets on AWS](https://aws.amazon.com/earth/).

**Comment by vijayaratha** [comment]
I suspect this issue is related to this https://github.com/pywren/pywren/issues/253. Also I tried pywren with lxml module too.I get same issue. Pywren could not serialise some 3rd party modules.As pointed in this twitter link  https://twitter.com/stochastician/status/907264445763567616, I edited pywren.runtime json configuration to include my modules. But still no success

**Comment by ericmjonas** [comment]
Right now, pywren is unable to serialize certain third party modules that
are c extensions; for these we necessitate a separate runtime. We're
working on making this better but it's complicated :)

**Comment by vijayaratha** [comment]
Thanks Eric. So, Do you have any plan to include this feature in your near future release?
Looks this is a major blocker to use Pywren library in a production environment.

**Comment by ericmjonas** [comment]
Yes, although it's still an active research area. I think it's unlikely we'll ever be able to reliably ship c extensions over the wire, because you might be on a mac/windows (common use cases!) and linux can't handle a shared lib. So we're working on two things in parallel: 

0. Make bigger more inclusive runtimes, that are more likely to contain the kitchen sink of what people want (this requires #2 below) 
1. the ability for a user to take an anaconda env and package it up as an environment
2. the ability to do some crazy stuff behind the scenes to handle the fact that this environment is probably too large for /tmp on lambda

It's just complex and has a lot of moving pieces. But we're hoping to get it in by the end of the summer.

**Comment by vijayaratha** [comment]
Thanks Eric

**Comment by tomwhite** [comment]
@Vaishaal, @ericmjonas that's great - thanks for the link

**Comment by tomwhite** [comment]
@ericmjonas and yes, would love to see the beta code if that's different

**Comment by tomwhite** [comment]
@cwharland thanks for the pointers - very useful.

Meanwhile I've made a start with building a runtime here (warning, very brittle code): https://github.com/tomwhite/runtimes/tree/custom
