### ISSUE TITLE
AccessDenied after installation with default settings?

### ISSUE THREAD

**Issue by msm-code** [pywren/pywren#232]
I'm trying to set up amazon and pywren, and I'm out of ideas.

I created new IAM user, gave him full (Admin) permissions, and run pywren-setup script (few times, because at first I tried without IAM user).

The result is:
```
╰─$ pywren-setup                                                                                         
This is the PyWren interactive setup script                                              
Your AWS configuration appears to be set up, and your account ID is 370942689422                    
This interactive script will set up your initial PyWren configuration.                                 
If this is the first time you are using PyWren then accepting the defaults should be fine.
What is your default aws region? [us-west-2]: eu-central-1                                               
Location for config file:  [/home/msm/.pywren_config]:                            
PyWren requires an s3 bucket to store intermediate data. What s3 bucket would you like to use? [msm-pywren-437]:
Bucket does not currently exist, would you like to create it? [Y/n]:                     
PyWren prefixes every object it puts in S3 with a particular prefix.                                     
PyWren s3 prefix:  [pywren.jobs]:                                                                            
Would you like to configure advanced PyWren properties? [y/N]:                                 
PyWren standalone mode uses dedicated AWS instances to run PyWren tasks. This is more flexible, but more expensive with fewer simultaneous workers.
Would you like to enable PyWren standalone mode? [y/N]:                                                 
Creating config /home/msm/.pywren_config                                                                   
new default file created in /home/msm/.pywren_config                                                
lambda role is pywren_exec_role_1                                                                        
Creating bucket msm-pywren-437.                                                                                      
Creating role.                                                                                 
Deploying lambda.                                                                       
function exists, updating                                                                                                                                                     
Pausing for 10 sec for changes to propagate.                                                   
Traceback (most recent call last):                                       
  File "/usr/local/bin/pywren-setup", line 11, in <module>                                               
    load_entry_point('pywren==0.3.0', 'console_scripts', 'pywren-setup')()            
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__                     
    return self.main(*args, **kwargs)                                      
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main                                     
    rv = self.invoke(ctx)                                                                        
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke       
    return ctx.invoke(self.callback, **ctx.params)                                                       
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke                     
    return callback(*args, **kwargs)                                                                     
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func   
    return f(get_current_context(), *args, **kwargs)                                                     
  File "/usr/local/lib/python2.7/dist-packages/pywren/scripts/setupscript.py", line 208, in interactive_setup   
    ctx.invoke(pywrencli.test_function)                                    
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)                
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func                
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pywren/scripts/pywrencli.py", line 374, in test_function
    wrenexec = pywren.default_executor(config=config)
  File "/usr/local/lib/python2.7/dist-packages/pywren/wren.py", line 21, in default_executor
    return lambda_executor(**kwargs)                
  File "/usr/local/lib/python2.7/dist-packages/pywren/wren.py", line 37, in lambda_executor              
    return Executor(invoker, config, job_max_runtime)
  File "/usr/local/lib/python2.7/dist-packages/pywren/executor.py", line 40, in __init__
    self.runtime_meta_info = runtime.get_runtime_info(config['runtime'])
  File "/usr/local/lib/python2.7/dist-packages/pywren/runtime.py", line 10, in get_runtime_info
    runtime_meta = storage.get_runtime_info(runtime_config)
  File "/usr/local/lib/python2.7/dist-packages/pywren/storage/storage.py", line 112, in get_runtime_info
    json_str = handler.get_object(key)              
  File "/usr/local/lib/python2.7/dist-packages/pywren/storage/s3_backend.py", line 42, in get_object
    raise e                                                                                              
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
                              
```

`pywren test_function` throws the same error btw. Is this a known problem (couldn't find anything too similar on the internet, but I'm new to AWS so I'm probably wrong)

**Comment by Vaishaal** [comment]
Does the setup work without an IAM user? (If you run the setup as root)

**Comment by Vaishaal** [comment]
Can you also try saying yes to "Advanced Properties" and give the lambda a different name (such as pywren_2)

**Comment by msm-code** [comment]
Unfortunately, the same error (for both IAM user and admin).

I'll investigate further and update this issue (maybe a problem with my configuration? Though I used plain new account).

**Comment by Vaishaal** [comment]
Can you paste ~/.pywren_config here?

**Comment by Vaishaal** [comment]
can you try aws s3 ls s3://pywren-public-eu-central-1

**Comment by msm-code** [comment]
```
╰─$ aws s3 ls s3://pywren-public-eu-central-1       

An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied                   
```

For the record, 

```
aws s3 ls s3://pywren-public-us-west-1
```

does work.

**Comment by Vaishaal** [comment]
great! thats the bug let me see if I can fix it. Is eu-central the region you want to use?

**Comment by msm-code** [comment]
Yes (although I don't have a very strong preference - I just selected it because that's region closest to me).

Thanks for help so far and fast answers!

**Comment by Vaishaal** [comment]
It looks like we forgot to mark the region public, we are doing it right now

**Comment by Vaishaal** [comment]
let me know if the setup works with the us-west region

**Comment by msm-code** [comment]
> let me know if the setup works with the us-west region

```
function returned: Hello world
```

Great, looks like it does! (I had to change ~/.aws/config to us-west-2)

Thanks for help. I don't need low latency, so as far as I understand, us-west is as good as eu-central, right?

(Closing issue as I guess you've marked region as public already)

**Comment by g-io** [comment]
I seem to see the same issue with eu-west-1.
From the code I see that the bucket to access is pywren-runtimes-public-eu-west-1, however:
```
$ aws s3 ls pywren-runtimes-public-eu-west-1
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
