### ISSUE TITLE
Pywren executor not thread-safe due to shared ModuleDependencyAnalyzer

### ISSUE THREAD

**Issue by ericl** [pywren/pywren#237]
If you call into the executor concurrently from multiple threads, the list of modules sent with each function can be corrupted, and you get errors like `cannot import pywren` from the Lambda. This is because the module dependency analyzer in `serialize/serialize.py` is shared.

Possible fixes:
- Don't cache the dependency analyzer and create a new one per `__call__` of SerializerIndependent.
- Lock around uses of the dependency analyzer

cc @ooq

**Comment by Vaishaal** [comment]
Great find!  I think we should create a new dependency analyzer per __call__. Do you have a failing code snippet we can use to test?

**Comment by ericl** [comment]
Sure, the following snippet will fail with

```
[<pywren.future.ResponseFuture object at 0x7ff38c39fe80>, <pywren.future.ResponseFuture object at 0x7ff38c22b0b8>, <pywren.future.ResponseFuture object at 0x7ff38c1cff98>, <pywren.future.ResponseFuture object at 0x7ff38c055208>, <pywren.future.ResponseFuture object at 0x7ff38c22bf98>, <pywren.future.ResponseFuture object at 0x7ff38c22b048>, <pywren.future.ResponseFuture object at 0x7ff38c247588>, <pywren.future.ResponseFuture object at 0x7ff38c0bfb00>, <pywren.future.ResponseFuture object at 0x7ff38c2470b8>, <pywren.future.ResponseFuture object at 0x7ff38c2474a8>]
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(r.result())
  File "/usr/local/lib/python3.5/dist-packages/pywren/future.py", line 202, in result
    reraise(*self._traceback)
  File "/home/eric/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/var/task/jobrunner.py", line 29, in <module>
ImportError: No module named 'pywren'
```

```
import pywren
from multiprocessing.pool import ThreadPool

pool = ThreadPool(10)
exec = pywren.default_executor()
results = pool.map(
    lambda i: exec.call_async(lambda f: f[0] + f[1], [2, 2]),
    range(10))
print(results)
for r in results:
    print(r.result())
```

**Comment by ericmjonas** [comment]
This feels like an antipattern. Why are you doing this? Threads are a bad
idea in general.

**Comment by ericmjonas** [comment]
Regardless I think we'd consider a pull requests with locks ? Our model has
been a separate executor per thread process, right ?

**Comment by ericl** [comment]
We have a multi-threaded server that interacts with pywren. We could lock around pywren invocations or use multiple pywren executors, but it's somewhat more convenient if executors are thread-safe (and they seem to be sans this small piece).
