### ISSUE TITLE
pywren-setup returns pywren.storage.exceptions.StorageNoSuchKeyError: No such key pywren.runtimes/default_2.7.meta.json found in storage.

### ISSUE THREAD

**Issue by chinesebox** [pywren/pywren#256]
I try to use pywren unfortunetly without luck.
According to http://pywren.io/pages/gettingstarted.html I do following steps from 

1) pip install awscli
2) aws configure
3) assigned permissions from default_pywren_user_permissions.json
additionaly added:
iam:ListRoles
4) pip install pywren I also tried installing from repo
5) pywren-setup
output:

This is the PyWren interactive setup script
Your AWS configuration appears to be set up, and your account ID is ***
This interactive script will set up your initial PyWren configuration.
If this is the first time you are using PyWren then accepting the defaults should be fine.
What is your default aws region? [us-west-2]: eu-west-1
Location for config file:  [/root/.pywren_config]:
/root/.pywren_config already exists, would you like to overwrite? [y/N]: y
PyWren requires an s3 bucket to store intermediate data. What s3 bucket would you like to use? [root-pywren-557]: y
PyWren prefixes every object it puts in S3 with a particular prefix.
PyWren s3 prefix:  [pywren.jobs]:
Would you like to configure advanced PyWren properties? [y/N]: n
PyWren standalone mode uses dedicated AWS instances to run PyWren tasks. This is more flexible, but more expensive with fewer simultaneous workers.
Would you like to enable PyWren standalone mode? [y/N]: n
Creating config /root/.pywren_config
new default file created in /root/.pywren_config
lambda role is pywren_exec_role_1
Creating role.
Using existing IAM role...
Deploying lambda.
function exists, updating
Pausing for 10 sec for changes to propagate.
Traceback (most recent call last):
  File "/usr/local/bin/pywren-setup", line 9, in <module>
    load_entry_point('pywren==0.3.0', 'console_scripts', 'pywren-setup')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/scripts/setupscript.py", line 224, in interactive_setup
    ctx.invoke(pywrencli.test_function)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/scripts/pywrencli.py", line 400, in test_function
    wrenexec = pywren.default_executor(config=config)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/wren.py", line 48, in default_executor
    return lambda_executor(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/wren.py", line 64, in lambda_executor
    return Executor(invoker, config, job_max_runtime)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/executor.py", line 56, in __init__
    self.runtime_meta_info = runtime.get_runtime_info(config['runtime'])
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/runtime.py", line 26, in get_runtime_info
    runtime_meta = storage.get_runtime_info(runtime_config)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/storage/storage.py", line 128, in get_runtime_info
    json_str = handler.get_object(key)
  File "/usr/local/lib/python2.7/dist-packages/pywren-0.3.0-py2.7.egg/pywren/storage/s3_backend.py", line 56, in get_object
    raise StorageNoSuchKeyError(key)
pywren.storage.exceptions.StorageNoSuchKeyError: No such key pywren.runtimes/default_2.7.meta.json found in storage.

I also tried set s3 bucket as public but output always is the same.
Do I missing something?

**Comment by bethcraig100178** [comment]
Hi, did you find a solution to this? Am getting this error today, thanks

**Comment by chinesebox** [comment]
unfortunately I gave up
