### ISSUE TITLE
Role with name pywren_exec_role_1 already exists.

### ISSUE THREAD

**Issue by bethcraig100178** [pywren/pywren#262]
Hi,

I am trying to set-up pywren on my laptop. Getting the following error after intially trying to set-up and getting other errors (pwd package)

C:\Users\bethc>pywren-setup
This is the PyWren interactive setup script
Your AWS configuration appears to be set up, and your account ID is XXXX
This interactive script will set up your initial PyWren configuration.
If this is the first time you are using PyWren then accepting the defaults should be fine.
What is your default aws region? [us-west-2]: eu-west-1
Location for config file:  [C:\Users\bethc/.pywren_config]:
C:\Users\bethc/.pywren_config already exists, would you like to overwrite? [y/N]: y
PyWren requires an s3 bucket to store intermediate data. What s3 bucket would you like to use? [bethc-pywren-566]:
Bucket does not currently exist, would you like to create it? [Y/n]: Y
PyWren prefixes every object it puts in S3 with a particular prefix.
PyWren s3 prefix:  [pywren.jobs]:
Would you like to configure advanced PyWren properties? [y/N]: N
PyWren standalone mode uses dedicated AWS instances to run PyWren tasks. This is more flexible, but more expensive with fewer simultaneous workers.
Would you like to enable PyWren standalone mode? [y/N]: y
Creating config C:\Users\bethc/.pywren_config
new default file created in C:\Users\bethc/.pywren_config
lambda role is pywren_exec_role_1
Creating bucket bethc-pywren-566.
Creating role.
Traceback (most recent call last):
  File "c:\users\bethc\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\bethc\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\bethc\Anaconda2\Scripts\pywren-setup.exe\__main__.py", line 9, in <module>
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\scripts\setupscript.py", line 209, in interactive_setup
    ctx.invoke(pywrencli.create_role)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\scripts\pywrencli.py", line 147, in create_role
    AssumeRolePolicyDocument=json_policy)
  File "c:\users\bethc\anaconda2\lib\site-packages\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "c:\users\bethc\anaconda2\lib\site-packages\botocore\client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\botocore\client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name pywren_exec_role_1 already exists.

**Comment by manu2000** [comment]
*For the pwd error, please refer to #259, I have provided a temporary fix there.

*For the Role error, if role is already set up then you can either:
a) go through the last two steps of the [manual set up process](http://pywren.io/pages/gettingstarted.html). You might have to change the bucket name in the config file if you go through the manual process. 
b) delete the role on aws website and run interactive set up again. To delete the role, go to aws website, search for IAM in services and select Roles from left sidebar.

Let me know if the setup finishes successfully, because I am getting no module named pywren error #242

**Comment by bethcraig100178** [comment]
Thanks i will try. Should have clarified, I found the fix for pwd

**Comment by bethcraig100178** [comment]
I deleted the IAM role on the aws site and that fixed the error.
But I am back to getting this one (#256)

pywren.storage.exceptions.StorageNoSuchKeyError: No such key pywren.runtimes/default_2.7.meta.json found in storage.


This is the PyWren interactive setup script
Your AWS configuration appears to be set up, and your account ID is XXX
This interactive script will set up your initial PyWren configuration.
If this is the first time you are using PyWren then accepting the defaults should be fine.
What is your default aws region? [us-west-2]: eu-west-1
Location for config file:  [C:\Users\bethc/.pywren_config]:
C:\Users\bethc/.pywren_config already exists, would you like to overwrite? [y/N]: y
PyWren requires an s3 bucket to store intermediate data. What s3 bucket would you like to use? [bethc-pywren-359]:
Bucket does not currently exist, would you like to create it? [Y/n]: Y
PyWren prefixes every object it puts in S3 with a particular prefix.
PyWren s3 prefix:  [pywren.jobs]:
Would you like to configure advanced PyWren properties? [y/N]: N
PyWren standalone mode uses dedicated AWS instances to run PyWren tasks. This is more flexible, but more expensive with fewer simultaneous workers.
Would you like to enable PyWren standalone mode? [y/N]: N
Creating config C:\Users\bethc/.pywren_config
new default file created in C:\Users\bethc/.pywren_config
lambda role is pywren_exec_role_1
Creating bucket bethc-pywren-359.
Creating role.
Deploying lambda.
function exists, updating
Pausing for 10 sec for changes to propagate.
Traceback (most recent call last):
  File "c:\users\bethc\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\bethc\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\bethc\Anaconda2\Scripts\pywren-setup.exe\__main__.py", line 9, in <module>
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\scripts\setupscript.py", line 219, in interactive_setup
    ctx.invoke(pywrencli.test_function)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\scripts\pywrencli.py", line 374, in test_function
    wrenexec = pywren.default_executor(config=config)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\wren.py", line 21, in default_executor
    return lambda_executor(**kwargs)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\wren.py", line 37, in lambda_executor
    return Executor(invoker, config, job_max_runtime)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\executor.py", line 40, in __init__
    self.runtime_meta_info = runtime.get_runtime_info(config['runtime'])
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\runtime.py", line 10, in get_runtime_info
    runtime_meta = storage.get_runtime_info(runtime_config)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\storage\storage.py", line 112, in get_runtime_info
    json_str = handler.get_object(key)
  File "c:\users\bethc\anaconda2\lib\site-packages\pywren\storage\s3_backend.py", line 40, in get_object
    raise StorageNoSuchKeyError(key)
pywren.storage.exceptions.StorageNoSuchKeyError: No such key pywren.runtimes/default_2.7.meta.json found in storage.
