### ISSUE TITLE
pywren print_latest_logs Errors

### ISSUE THREAD

**Issue by dderiso** [pywren/pywren#303]
Thanks for maintaining such a great project!

1. The command

```
pywren print_latest_logs
```

results in the following error, 

```
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
```

2. A second symptom of the problems is that the following command hangs, without any errors or debug level messages
```
pywren test_function
```

Both 1 and 2 occur in standalone and default mode.

Here's the full dump:

```
Traceback (most recent call last):
  File "~/anaconda3/bin/pywren", line 11, in <module>
    load_entry_point('pywren==0.4.0', 'console_scripts', 'pywren')()
  File "~/anaconda3/lib/python3.7/site-packages/pywren-0.4.0-py3.7.egg/pywren/scripts/pywrencli.py", line 711, in main
    return cli() # pylint: disable=no-value-for-parameter
  File "~/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "~/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "~/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "~/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "~/anaconda3/lib/python3.7/site-packages/pywren-0.4.0-py3.7.egg/pywren/scripts/pywrencli.py", line 480, in print_latest_logs
    descending=True)
  File "~/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "~/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
```

Also, if it helps, 
```
pywren log_url
```

returns 

```
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logStream:group=/aws/lambda/pywren_1
```

I suspect that 
```
/aws/lambda/pywren_1
```
is not a feasible log stream group name since I can't seem to create it manually on the cloudstream website. It will, however, allow me to create logs stream group names without nesting or slashes.

**Comment by wanghc78** [comment]
@dderiso Have you solved the problem `pywren test_function` hang there forever? I met the same problem. 

And here is the full log after turning on `export PYWREN_LOGLEVEL=INFO`.

```
$ pywren test_function
2019-02-21 00:54:15,091 [INFO] pywren.executor: using serializer with meta-supplied preinstalls
2019-02-21 00:54:21,547 [INFO] pywren.executor: map 2be7bd4e-bf16-4ded-91e4-55838de41112 00000 apply async
2019-02-21 00:54:21,548 [INFO] pywren.executor: call_async 2be7bd4e-bf16-4ded-91e4-55838de41112 00000 lambda invoke 
2019-02-21 00:54:22,008 [INFO] pywren.executor: call_async 2be7bd4e-bf16-4ded-91e4-55838de41112 00000 lambda invoke complete
2019-02-21 00:54:22,018 [INFO] pywren.executor: map invoked 2be7bd4e-bf16-4ded-91e4-55838de41112 00000 pool join
```

For the log issue, after manual creating the log group, */aws/lambda/pywren_1* and a log stream. It will not report an error. But still no logs there.

**Comment by dderiso** [comment]
I’m sorry you’re hitting this wall. This library needs better documentation
and test cases, (which are hopefully in the pipeline). The issue may be
related to permissions. You should check that you have assigned permissions
for reading and writing to S3. Note that you should assign these
permissions to your “lambda user” not your “root user” account. If this
fixes the issue, you should see data populated in the S3 bucket you
created, which should be visible from the S3 dashboard. Hope this helps!

**Comment by wanghc78** [comment]
Great, thank you! Problem solved by attaching the S3 permissions. 

Yes, it needs documenting this part. And the pywren-setup script may also attach the permission when creating the role
