### ISSUE TITLE
Forbidden on downloading runtime

### ISSUE THREAD

**Issue by semitom** [pywren/pywren#309]
`pywren test_function` gives:
```
Traceback (most recent call last):
  File "/var/task/wrenhandler.py", line 300, in generic_handler
    runtime_s3_key_used, delete_old_runtimes)
  File "/var/task/wrenhandler.py", line 121, in download_runtime_if_necessary
    Key=runtime_s3_key)
  File "/var/runtime/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

Traceback (most recent call last):
  File "/home/user/venv/bin/pywren", line 10, in <module>
    sys.exit(main())
  File "/home/user/venv/lib/python3.5/site-packages/pywren/scripts/pywrencli.py", line 711, in main
    return cli() # pylint: disable=no-value-for-parameter
  File "/home/user/venv/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/venv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/pywren/scripts/pywrencli.py", line 457, in test_function
    res = fut.result(storage_handler=wrenexec.storage)
  File "/home/user/venv/lib/python3.5/site-packages/pywren/future.py", line 211, in result
    raise Exception(exception_str, *exception_args)
Exception: ('An error occurred (403) when calling the HeadObject operation: Forbidden', 'An error occurred (403) when calling the HeadObject operation: Forbidden')
```

```
runtime:
    s3_bucket: pywren-runtimes-public-us-west-1
    s3_key: pywren.runtimes/default_3.5.meta.json
```

Strange enough the `default_3.7.meta.json` runtime seems to work still.

**Comment by andrewmzhang** [comment]
Can confirm a similar issue on 3.6. Can also confirm that 3.7 works fine. 

It seems that when the Lambda function tries to download the runtime, it cant call head_object on this bucket and key combination. 
``` 
# runtime_s3_bucket = pywren-public-us-west-2
# runtime_s3_key = 6eb2fa-pywren.runtimes/default_3.6.tar.gz.0077
runtime_meta = s3_client.head_object(Bucket=runtime_s3_bucket,
                                         Key=runtime_s3_key)
```

**Comment by andrewmzhang** [comment]
```
aws s3 ls s3://pywren-runtimes-public-us-west-2/pywren.runtimes/
2018-11-04 17:00:01      10697 3.7-default.meta.json
2018-11-04 16:59:29  173495184 3.7-default.tar.gz
2018-11-04 17:00:25      10697 3.7-minimal.meta.json
2018-11-04 17:00:01  173497078 3.7-minimal.tar.gz
2018-11-02 23:32:48      17197 datascience_3.6.meta.json
2018-11-02 23:32:48      10101 deep_cpu_3.6.meta.json
2018-11-02 23:32:48      10131 deep_gpu_3.6.meta.json
2018-11-02 23:32:48      18273 default_2.7.meta.json
2018-11-02 23:32:48      16455 default_3.4.meta.json
2018-11-02 23:32:49      16642 default_3.5.meta.json
2018-11-02 23:32:49      16677 default_3.6.meta.json
2018-11-13 22:19:27      10705 default_3.7.meta.json
2018-11-09 18:33:40  171705928 default_3.7.tar.gz
2018-11-02 23:32:49      18056 default_vaishaal_3.6.meta.json
2018-11-02 23:32:49       8092 micro_3.6.meta.json
2018-11-02 23:32:49      17372 minimal_2.7.meta.json
2018-11-02 23:32:49      15852 minimal_3.4.meta.json
2018-11-02 23:32:49      15970 minimal_3.5.meta.json
2018-11-02 23:32:49      16003 minimal_3.6.meta.json
2018-11-13 22:20:31      10705 minimal_3.7.meta.json
2018-11-09 18:35:15  171696691 minimal_3.7.tar.gz
2018-11-02 23:32:49       9639 mri_3.6.meta.json
2018-11-02 23:32:49       9398 opt_3.6.meta.json
2018-11-02 23:32:49      12856 pydata_3.6.meta.json
2018-11-02 23:32:49      13200 pytorch_gpu_cu90_3.6.meta.json
2018-11-02 23:32:49      13234 pytorch_gpu_master_3.6.meta.json
2018-11-02 23:32:50      13239 pytorch_gpu_master_v100_3.6.meta.json
2018-11-04 16:50:51      10847 pywren_runtime-3.7-default.meta.json
2018-11-04 16:50:30  173501428 pywren_runtime-3.7-default.tar.gz
2018-11-04 16:51:41      10847 pywren_runtime-3.7-minimal.meta.json
2018-11-04 16:50:52  173499747 pywren_runtime-3.7-minimal.tar.gz
2018-11-02 23:32:50      17684 tf_cpu_2.7.meta.json
2018-11-02 23:32:50      21468 too_big_do_not_use_2.7.meta.json
2018-11-02 23:32:50      19388 too_big_do_not_use_3.4.meta.json
2018-11-02 23:32:50      19566 too_big_do_not_use_3.5.meta.json
2018-11-02 23:32:50      19601 too_big_do_not_use_3.6.meta.json
2018-11-09 18:35:14      12808 too_big_do_not_use_3.7.meta.json
2018-11-09 18:34:13  386371706 too_big_do_not_use_3.7.tar.gz
```

It appears that all but the python 3.7 tar.gz runtimes have been removed.

**Comment by ericmjonas** [comment]
Ok this is weird; last week we changed the legacy pywren buckets to requester-pays because someone in the EU region was using the `us-west-2` bucket and it was costing us $2000/month. After extensive debate, we couldn't see any other way. But these were the _legacy_ buckets, not the `pywren-runtimes-public-*` buckets. @andrewmzhang and @semitom can you both confirm you're trying to use the new buckets?

**Comment by andrewmzhang** [comment]
I'm a bit confused as to what you want me to confirm? It looks like all the bucket requests are being pulled from "pywren-runtimes-public-us-west-2" bucket, at least when I try to use python 2.7 (I realize the above report I made was using python 3.6, but that was because I made a mistake locally with python versions). 

Also where might I find a python 2.7 pywren runtime? Looks like the s3-bucket still has the json for 2.7 but not the tar.gz file for it.

**Comment by JoostvDoorn** [comment]
We are also in the EU, and found that the only place for working runtimes is us-west-2. Where should we get the runtimes from when using eu-west-1?

**Comment by ericmjonas** [comment]
@andrewmzhang Can you confirm you can see the indicated object with your account via
 `aws s3 ls s3://pywren-public-us-west-2/6eb2fa-pywren.runtimes/default_3.6.tar.gz.0077` 

Also sorry everyone for the slow replies here, I have a conference deadline in three days and family visiting and am really slammed.

**Comment by Vaishaal** [comment]
Ok I think @ericmjonas  and I have narrowed this down to a combination of a bug in the S3 urls in our meta.json files + requester pays being turned on. I'm looking into a fix right now, hopefully should be resolved in like 24-48h.

**Comment by andrewmzhang** [comment]
@ericmjonas 

I ran the command you specified, I get access denied. Here's the output if you want it

```
~$ aws s3 ls s3://pywren-public-us-west-2/6eb2fa-pywren.runtimes/default_3.6.tar.gz.0077

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
~$ aws s3 ls s3://pywren-public-us-west-2/pywren.runtimes/default_3.6.tar.gz

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by ducnguyenAstro** [comment]
Guys,

This drives me crazy too,  I have a daily running task that has been running pywren like a charm for many months, lately stopped working. 

When I try to re-setup pywren, it never succeed:
Traceback (most recent call last):
  File "/usr/local/bin/pywren-setup", line 11, in <module>
    sys.exit(interactive_setup())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pywren/scripts/setupscript.py", line 222, in interactive_setup
    ctx.invoke(pywrencli.test_function)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pywren/scripts/pywrencli.py", line 457, in test_function
    res = fut.result(storage_handler=wrenexec.storage)
  File "/usr/local/lib/python3.5/dist-packages/pywren/future.py", line 211, in result
    raise Exception(exception_str, *exception_args)
Exception: ('An error occurred (403) when calling the HeadObject operation: Forbidden', 'An error occurred (403) when calling the HeadObject operation: Forbidden')

runtime:
    s3_bucket: pywren-runtimes-public-us-west-1
    s3_key: pywren.runtimes/default_3.5.meta.json

Do you guys have any band-aids for now till the problem is solved from root cause?

**Comment by MitchellMittman** [comment]
Hi... has this issue been resolved? I'm still getting it.

**Comment by Vaishaal** [comment]
Can you try now. I think I fixed the permissions on our side
