### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by sreeram-gsan** [pywren/pywren#318]
I installed PyWren 0.4.0 with Python 3.9. I am getting a "TypeError: an integer is required (got type bytes)" error when importing PyWren. The following is the stack trace

Traceback (most recent call last):
  File "/Users/userx/Documents/Jupyter/venv/bin/pywren", line 5, in <module>
    from pywren.scripts.pywrencli import main
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/__init__.py", line 20, in <module>
    from pywren.wren import * # pylint: disable=wildcard-import
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/wren.py", line 25, in <module>
    from pywren.executor import Executor
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/executor.py", line 35, in <module>
    from pywren.serialize import serialize, create_mod_data
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/serialize/__init__.py", line 33, in <module>
    from pywren.serialize.serialize import SerializeIndependent
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/serialize/serialize.py", line 51, in <module>
    from pywren.serialize.cloudpickle import CloudPickler
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/serialize/cloudpickle/__init__.py", line 36, in <module>
    from pywren.serialize.cloudpickle.cloudpickle import CloudPickler
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/serialize/cloudpickle/cloudpickle.py", line 146, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/Users/userx/Documents/Jupyter/venv/lib/python3.9/site-packages/pywren/serialize/cloudpickle/cloudpickle.py", line 127, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by buildfail** [comment]
save this as patch.diff in the path for cloudpickle.py then execute 

https://gist.githubusercontent.com/buildfail/3b7bebd4999bc66def7b288800cd31ab/raw/2cf3efdc4dedbd56e4992624402aa9cba2f9e912/patch.diff

git apply patch.diff

**Comment by buildfail** [comment]
i fucking hate git markdown

**Comment by florianlaws** [comment]
I can confirm that @buildfail 's patch enables me to run pywren-setup without this type error.
