### ISSUE TITLE
ValueError: could not register funciton after 10 tries

### ISSUE THREAD

**Issue by raj1605** [pywren/pywren#321]
```
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Pausing for 5 seconds for changes to propagate.
Traceback (most recent call last):
  File "/home/ubuntu/Environments/numpywren/bin/pywren", line 11, in <module>
    load_entry_point('pywren==0.4.0', 'console_scripts', 'pywren')()
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/pywren-0.4.0-py3.7.egg/pywren/scripts/pywrencli.py", line 711, in main
    return cli() # pylint: disable=no-value-for-parameter
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/click-8.1.2-py3.7.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/click-8.1.2-py3.7.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/click-8.1.2-py3.7.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/click-8.1.2-py3.7.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/click-8.1.2-py3.7.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/click-8.1.2-py3.7.egg/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/Environments/numpywren/lib/python3.7/site-packages/pywren-0.4.0-py3.7.egg/pywren/scripts/pywrencli.py", line 352, in deploy_lambda
    raise ValueError("could not register funciton after 10 tries")
ValueError: could not register funciton after 10 tries
```

I'm trying to run pywren-setup, but the setup throws this error in the create_lambda command. Can you please help me in debugging this issue.

**Comment by sjswi** [comment]
python2.7 is not supported now, you should change deploy_lamdba
`lambclient.create_function(FunctionName=FUNCTION_NAME,
                                           Handler=pywren.wrenconfig.AWS_LAMBDA_HANDLER_NAME,
                                           Runtime="python3.9",
                                           MemorySize=MEMORY,
                                           Timeout=TIMEOUT,
                                           Role=ROLE,
                                           Code={'ZipFile' : file_like_object.getvalue()})`
in pywrencli.py

**Comment by sjswi** [comment]
To run this program，you must add a [layer](https://aws.amazon.com/cn/premiumsupport/knowledge-center/lambda-import-module-error-python/) to lambda function. And then you should modify wrenhandler.py. 
modify `from . import wrenutil # pylint: disable=relative-import
    from . import version  # pylint: disable=relative-import`
to `from pywren import wrenutil, version.`. Finally you should choose python3.7
