### ISSUE TITLE
NoSuchBucket: `pywren-runtimes-public-us-west-2` does not exists

### ISSUE THREAD

**Issue by GindaChen** [pywren/pywren#322]
I'm trying to setup pywren in my local machine and run some hello-world task. i hit the same error `NoSuchBucket`, and found that it seems like the bucket `pywren-runtimes-public-us-west-2` is not longer accessible.

Specifically:
<details>
<summary>`pywren-setup` will always throw `NoSuchBucket` at the end</summary>

```
$ pywren-setup
This is the PyWren interactive setup script
...
... # Omit some setup
...
Creating role.
Using existing IAM role...
Deploying lambda.
function exists, updating
Pausing for 10 sec for changes to propagate.
Traceback (most recent call last):
  File "/Users/mike/.pyenv/versions/3.7.10/bin/pywren-setup", line 8, in <module>
    sys.exit(interactive_setup())
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/scripts/setupscript.py", line 222, in interactive_setup
    ctx.invoke(pywrencli.test_function)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/scripts/pywrencli.py", line 452, in test_function
    wrenexec = pywren.default_executor(config=config)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/wren.py", line 48, in default_executor
    return lambda_executor(**kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/wren.py", line 66, in lambda_executor
    return Executor(invoker, config, job_max_runtime)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/executor.py", line 56, in __init__
    self.runtime_meta_info = runtime.get_runtime_info(config['runtime'])
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/runtime.py", line 26, in get_runtime_info
    runtime_meta = storage.get_runtime_info(runtime_config)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/storage/storage.py", line 140, in get_runtime_info
    json_str = handler.get_object(key)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/storage/s3_backend.py", line 58, in get_object
    raise e
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/storage/s3_backend.py", line 51, in get_object
    r = self.s3client.get_object(Bucket=self.s3_bucket, Key=key)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
```

</details>

<details>
<summary>In a simple `hello-world` example, the same error pops up</summary>

Code:
```python
import numpy as np
import pywren


def my_function(b):
    x = np.random.normal(0, b, 1024)
    A = np.random.normal(0, b, (1024, 1024))
    return np.dot(A, x)


pwex = pywren.default_executor()
res = pwex.map(my_function, np.linspace(10, 100, 200))
```

and error:
```
raceback (most recent call last):
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/storage/s3_backend.py", line 58, in get_object
    raise e
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pywren/storage/s3_backend.py", line 51, in get_object
    r = self.s3client.get_object(Bucket=self.s3_bucket, Key=key)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mike/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
```
</details>

**Comment by GindaChen** [comment]
I actually have a few questions:
1. Is the bucket no longer exists? Or is it that other regions (such as `east-1`) exists, but some regions are taken off?
2. What is the content in the `pywren-runtimes-public-us-west-2`? Is it somewhere in the repo that I can access and deploy on my own into some separate bucket?
